### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Insane96** [Insane-96/CarbonadoMod#2]
When editing .lang files, please don't remove %x like strings and §n too
Those are used respectively for in code values and for color

Need translators for ... well, translations

- [x] Italian
- [ ] German
- [ ] Spanish (MateusSkyrim via PM on CurseForge) (Needs update)
- [ ] French
- [ ] Turkish (#9) (needs update)
- [ ] Russian (#4) (#12) (needs update)
- [ ] Greek
- [ ] Korean
- [ ] Japanese
- [ ] Chinese (Simplified) (#5) (Needs Update)
- [ ] Chinese (Traditional) (#5) (Needs Update)
